### PR TITLE
Print update notification messages to stderr instead of stdout

### LINKED ISSUE #801: Bug: shell completion get's notice of updated version
**Describe the bug**

The following text is inserted into the top of the bash completion script which creates issues when sourcing

```
Note: A new version of Kit is available! You are using Kit v1.2.1. The latest version is v1.2.2.
      To see a list of changes, visit https://github.com/jozu-ai/kitops/releases/tag/v1.2.2
      To disable this notification, use 'kit version --show-update-notifications=false'
```

**To Reproduce**

1. `kit completion bash > kit.sh`
1. `source kit.sh`

**Version**

Version: 1.2.1

**Additional context**

If you print this message to `stderr` it would not be included in the script

### PR DESCRIPTION
**Pull request by amisevsk**
### Description
Print update notification message to stderr so that it is not included when output is redirected to file.

### Linked issues
Closes #801

### CODE REVIEW

File: pkg/output/logging.go [hunk 1]
```diff
@@ -73,6 +73,18 @@ func SafeDebugf(s string, args ...any) {
 	SafeLogf(LogLevelDebug, s, args...)
 }
 
+// SystemInfoLn is like Infoln except it logs to stderr. This should be used
+// for system messages such as update notifications
+func SystemInfoln(s any) {
+	loglnTo(stderr, LogLevelInfo, s)
+}
+
+// SystemInfof is like Infof except it logs to stder. This should be used
```
Comment (gorkem) [inline pkg/output/logging.go:82]: small typo
```suggestion
// SystemInfof is like Infof except it logs to stderr. This should be used
```

**Review by gorkem — APPROVED** [review]
